export {
  findGridPath,
  findGridPathDetailed,
  pathChunks,
  type PathGrid,
  type PathSearchOptions,
  type PathSearchResult,
  type PathSearchStatus,
} from './pathfinding';
export {
  adjacentChunks,
  chunkCoordinateForPosition,
  chunkKey,
  chunkOrigin,
  compareChunks,
  DEFAULT_CHUNK_SIZE,
  enumerateChunkRegion,
  localCoordinateForPosition,
  validateChunkSize,
  ChunkSpatialStore,
  createChunkSpatialStore,
} from './chunks';
export {
  BUILDING_FOOTPRINTS,
  buildingFootprint,
  exteriorEntranceCandidates,
  footprintCells,
  isExteriorEntrance,
  isInsideFootprint,
  selectExteriorEntrance,
  type EntranceSelectionOptions,
} from './footprints';
export { SeededRandom } from './random';
export { calculateCityDemand, calculateDemandChunk } from './demand';
export {
  DISTRICT_SEED_COSTS,
  DISTRICT_SEED_COST_GROWTH_FACTOR,
  getDistrictSeedCost,
  isDistrictSeedKindUnlocked,
} from './balance-rules';
export { calculateDistrictSeedInfluence, type DistrictSeedInfluenceInput } from './district-seeds';
export {
  CONSTRUCTION_PHASE_ORDER,
  DEFAULT_CONSTRUCTION_PHASE_DURATIONS,
  nextConstructionPhase,
  validateConstructionPhaseDurations,
} from './construction';
export {
  compareDevelopmentCandidates,
  compareDevelopmentBuildingTypes,
  DEVELOPMENT_BUILDING_TYPE_ORDER,
  DEVELOPMENT_SCORE_PRECISION,
  DEVELOPMENT_SCORE_WEIGHTS,
  scoreDevelopmentCandidate,
  type DevelopmentScoreInput,
  type DevelopmentScoreResult,
} from './developer';
export { createSimulation } from './simulation';
export {
  canonicalTrafficEdge,
  createTrafficTelemetry,
  DEFAULT_TRAFFIC_HISTORY_WINDOW_TICKS,
  trafficEdgeKey,
  tryCanonicalTrafficEdge,
  type TrafficEdgeIdentity,
  type TrafficTelemetry,
  type TrafficTelemetryCounters,
  type TrafficTelemetryOptions,
} from './traffic';
export {
  findNearestCompatiblePair,
  type PopulationAssignment,
  type PopulationAssignmentInput,
} from './population';
export {
  buildMovementProposals,
  compareMovementProposals,
  findDirectMovementSwapPairs,
  isMovementReplanDue,
  isMovementDeadlockRecoveryDue,
  MOVEMENT_DEADLOCK_RECOVERY_BLOCKED_TICKS,
  MOVEMENT_REPLAN_FIRST_WAIT_TICKS,
  MOVEMENT_REPLAN_INTERVAL_TICKS,
  movementPairKey,
  replanMovementRoute,
  resolveMovementReservations,
  type MovementBlockReason,
  type MovementCandidate,
  type MovementBlockedProposal,
  type MovementMove,
  type MovementProposal,
  type MovementProposalInput,
  type MovementReplanInput,
  type MovementReplanResult,
  type MovementResolution,
  type MovementResolutionInput,
  type MovementSwapPair,
} from './movement';
export type { ChunkCoordinate, GridPosition, GridRect } from '@idle-city/shared';
export type {
  AcceptedCommandResult,
  Building,
  BuildingOccupancy,
  BuildingType,
  ChunkActivationRejectionReason,
  ChunkActivationResult,
  ChunkRegion,
  ActivateChunkCommand,
  ActiveChunkSnapshot,
  CitizenActivity,
  CitizenSnapshot,
  CityDemand,
  CityMetrics,
  ConstructionPhase,
  ConstructionProject,
  CommandRejectionReason,
  CommandResult,
  DemandCell,
  DemandChunkSnapshot,
  DemandChunkSummary,
  DemandKind,
  DemandRegionQuery,
  DemandRegionSnapshot,
  DemandTotals,
  DevelopmentCandidate,
  DevelopmentReason,
  DevelopmentReasonCode,
  DistrictSeed,
  DistrictSeedKind,
  DistrictSeedPlacementPreview,
  LegacyCityDemand,
  PlaceDistrictSeedCommand,
  RejectedCommandResult,
  Simulation,
  SimulationConfig,
  SimulationSnapshot,
  SimulationStructuralCounters,
  TrafficEdgeSnapshot,
} from './types';
export type {
  DemandCalculationInput,
  DemandChunkCalculationInput,
  DemandCitizen,
  DemandSeedInfluence,
} from './demand';
